Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2023-11, with the labels that each got.

#441 Use the `debug` collector exporter instead of deprecated `logging` exporter
  .github/workflows/e2e/k8s/collector-helm-values.yml
Labels: Skip Changelog

#445 Remove duplicate offset declaration in net/http/server instrumentation
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
Labels: Skip Changelog

#448 Unify import of `semconv` to v1.21.0
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe_test.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
Labels: Skip Changelog

#443 Move `Event` into `probe` package
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe_test.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/probe/event.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/opentelemetry/controller.go
  internal/pkg/opentelemetry/id_generator.go
Labels: Skip Changelog

#447 Replace `inspect.StructField` with `structfield.ID`
  internal/tools/inspect/app.go
  internal/tools/inspect/cache.go
  internal/tools/inspect/cmd/offsetgen/main.go
  internal/tools/inspect/inspector.go
  internal/tools/inspect/manifest.go
Labels: Skip Changelog

#442 Add scope version
  CHANGELOG.md
  instrumentation.go
  internal/pkg/opentelemetry/controller.go
  internal/test/e2e/databasesql/traces.json
  internal/test/e2e/gin/traces.json
  internal/test/e2e/nethttp/traces.json
Labels: enhancement

#390 internal/pkg/instrumentors/utils: fix GetLinuxKernelVersion logic
  internal/pkg/instrumentation/utils/kernel.go
  internal/pkg/instrumentation/utils/kernel_test.go
Labels: Skip Changelog

#456 Fix examples build on docker-compose. Create go.mod from the Dockerfile
  examples/httpPlusdb/Dockerfile
  examples/httpPlusdb/README.md
  examples/rolldice/Dockerfile
Labels: Skip Changelog

#466 Increase the max length of context chain which is checked by get_pare…
  internal/include/go_context.h
Labels: Skip Changelog

#455 Fix target library version lookup for grpc server
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
Labels: bug, Skip Changelog

#467 Avoid stoppoing the instrumentor if library version parsing failed
  internal/pkg/process/module.go
Labels: Skip Changelog

#473 Improve bounds checks in append_item_to_slice
  internal/include/go_types.h
  internal/include/utils.h
  internal/pkg/instrumentation/bpf/database/sql/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/database/sql/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_x86.go
Labels: Skip Changelog

#452 Add the base implementation of the Probe
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/process/analyze.go
Labels: Skip Changelog

#453 Add end-to-end testing for gRPC client/server
  .github/dependabot.yml
  .github/workflows/kind.yml
  Makefile
  go.mod
  go.sum
  internal/test/e2e/grpc/Dockerfile
  internal/test/e2e/grpc/main.go
  internal/test/e2e/grpc/traces.json
  internal/test/e2e/grpc/verify.bats
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog

#482 Refactor database/sql probe to use base probe implementation
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
Labels: Skip Changelog

#481 Refactor gin probe to use base probe implementation
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe_test.go
Labels: Skip Changelog

#479 Refactor net/http server probe to use base probe implementation
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
Labels: Skip Changelog

#480 Refactor net/http client probe to use base probe implementation
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
Labels: Skip Changelog

#478 Refactor gRPC client probe to use base probe implementation
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/probe.go
Labels: Skip Changelog

#496 Remove the shared volume from examples
  examples/httpPlusdb/docker-compose.yaml
  examples/rolldice/docker-compose.yaml
Labels: Skip Changelog

#477 Refactor gRPC server probe to use base probe implementation
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
Labels: Skip Changelog

#502 Rename the decodeHeader uprobe in grpc server instrumentation
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
Labels: Skip Changelog

#501 Add probe manifest
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/probe/manifest.go
  internal/pkg/instrumentation/probe/manifest_test.go
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#503 Fallback to the single offset if possible and version can't be parsed
  internal/pkg/structfield/structfield.go
  internal/pkg/structfield/structfield_test.go
Labels: Skip Changelog

#506 Update helm install cmd for fixtures targ
  Makefile
Labels: bug, Skip Changelog

#508 Fix offset gen target
  internal/pkg/inject/offset_results.json
Labels: Skip Changelog

#512 Change server HTTP uprobed method to net/http.serverHandler.ServeHTTP
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/test/e2e/gin/traces.json
  internal/test/test_helpers/utilities.bash
Labels: Skip Changelog

#527 Add status code to the HTTP client probe
  Makefile
  internal/include/arguments.h
  internal/pkg/inject/offset_results.json
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/test/e2e/databasesql/traces.json
  internal/test/e2e/gin/traces.json
  internal/test/e2e/nethttp/traces.json
  internal/test/e2e/nethttp/verify.bats
  internal/tools/inspect/cmd/offsetgen/main.go
Labels: Skip Changelog

#528 Update jaeger image in getting-started
  docs/getting-started/jaeger.yaml
Labels: Skip Changelog
