Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2023-10, with the labels that each got.

#363 Call runtime.LockOSThread() before ptrace
  internal/pkg/process/analyze.go
Labels: Skip Changelog

#365 Bump Go version to 1.21.2
  .github/workflows/build.yaml
  .github/workflows/checks.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/kind.yml
  .github/workflows/offsets.yml
  Makefile
  examples/httpPlusdb/Dockerfile
  examples/rolldice/Dockerfile
  internal/pkg/inject/offset_results.json
  internal/test/e2e/databasesql/Dockerfile
  internal/test/e2e/gin/Dockerfile
  internal/test/e2e/nethttp/Dockerfile
Labels: Skip Changelog

#273 Replace offsets with offsetgen
  Makefile
  internal/pkg/inject/offset_results.json
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/inspect/app.go
  internal/tools/inspect/builder.go
  internal/tools/inspect/cache.go
  internal/tools/inspect/cmd/offsetgen/main.go
  internal/tools/inspect/cmd/offsetgen/verions.go
  internal/tools/inspect/inspector.go
  internal/tools/inspect/manifest.go
  internal/tools/inspect/render.go
  internal/tools/inspect/templates/google.golang.org/grpc/go.mod.tmpl
  internal/tools/inspect/templates/google.golang.org/grpc/main.go.tmpl
  internal/tools/inspect/templates/net/http/go.mod.tmpl
  internal/tools/inspect/templates/net/http/main.go.tmpl
  internal/tools/inspect/templates/runtime/go.mod.tmpl
  internal/tools/inspect/templates/runtime/main.go.tmpl
  internal/tools/offsets/binary/data_member.go
  internal/tools/offsets/binary/reader.go
  internal/tools/offsets/cache/cache.go
  internal/tools/offsets/downloader/go_wrapper.go
  internal/tools/offsets/downloader/remote_targz.go
  internal/tools/offsets/downloader/wrapper/go.mod.txt
  internal/tools/offsets/downloader/wrapper/go.modstd.txt
  internal/tools/offsets/downloader/wrapper/main.go.txt
  internal/tools/offsets/main.go
  internal/tools/offsets/target/target.go
  internal/tools/offsets/utils/cmd.go
  internal/tools/offsets/versions/go_list.go
  internal/tools/offsets/versions/golang_org.go
  internal/tools/offsets/versions/tools.go
  internal/tools/offsets/writer/writer.go
Labels: Skip Changelog

#369 Fix the make command in dependabot PR script
  .github/workflows/scripts/dependabot-pr.sh
Labels: Skip Changelog

#370 Rename instConfig_test.go to instrumentation_test.go
  instrumentation_test.go
Labels: Skip Changelog

#371 Update PID option precedence
  instrumentation.go
Labels: Skip Changelog

#382 Support stripped binaries
  internal/pkg/process/analyze.go
  internal/pkg/process/binary/binary.go
  internal/pkg/process/binary/funcs_nonstripped.go
  internal/pkg/process/binary/funcs_stripped.go
  internal/pkg/process/binary/ret_linux_amd64.go
  internal/pkg/process/binary/ret_linux_arm64.go
Labels: Skip Changelog

#385 Bump cilium/ebpf in internal/tools
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog

#373 Add a Get Started doc with three scenarios
  README.md
Labels: Skip Changelog

#395 Update Dockerfile
  Dockerfile
Labels: Skip Changelog

#399 Remove the errors pkg
  cli/main.go
  internal/pkg/errors/errors.go
  internal/pkg/process/discover.go
Labels: Skip Changelog

#388 Remove SYS_PTRACE
  .github/workflows/e2e/k8s/sample-job.yml
  CHANGELOG.md
  docs/getting-started/emojivoto-instrumented.yaml
Labels: documentation

#392 docs: Update compiling the project
  CONTRIBUTING.md
Labels: Skip Changelog

#400 Fix link in WithPID doc to Instrumentation
  instrumentation.go
Labels: documentation, Skip Changelog

#405 Rename api.go to instrumentor.go
  internal/pkg/instrumentors/instrumentor.go
Labels: Skip Changelog

#404 Move Manager into one file
  internal/pkg/instrumentors/manager.go
  internal/pkg/instrumentors/runner.go
Labels: Skip Changelog

#412 Install dependencies for dependabot-pr action
  .github/workflows/create-dependabot-pr.yml
Labels: bug, Skip Changelog

#406 Remove the InstrumentorContext
  internal/pkg/instrumentors/bpf/database/sql/probe.go
  internal/pkg/instrumentors/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentors/bpf/net/http/client/probe.go
  internal/pkg/instrumentors/bpf/net/http/server/probe.go
  internal/pkg/instrumentors/context/inst_context.go
  internal/pkg/instrumentors/instrumentor.go
  internal/pkg/instrumentors/manager.go
Labels: Skip Changelog

#394 Replace `internal/pkg/inject.Injector`
  internal/pkg/inject/consts.go
  internal/pkg/inject/consts_test.go
  internal/pkg/inject/injector.go
  internal/pkg/instrumentors/bpf/database/sql/probe.go
  internal/pkg/instrumentors/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentors/bpf/net/http/client/probe.go
  internal/pkg/instrumentors/bpf/net/http/server/probe.go
Labels: Skip Changelog

#401 Replace log pkg use with explicit loggers
  cli/main.go
  go.mod
  instrumentation.go
  internal/pkg/instrumentors/bpf/database/sql/probe.go
  internal/pkg/instrumentors/bpf/database/sql/probe_test.go
  internal/pkg/instrumentors/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentors/bpf/github.com/gin-gonic/gin/probe_test.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentors/bpf/net/http/client/probe.go
  internal/pkg/instrumentors/bpf/net/http/server/probe.go
  internal/pkg/instrumentors/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentors/bpffs/bpfsfs.go
  internal/pkg/instrumentors/manager.go
  internal/pkg/log/logger.go
  internal/pkg/opentelemetry/controller.go
  internal/pkg/process/allocate.go
  internal/pkg/process/analyze.go
  internal/pkg/process/binary/binary.go
  internal/pkg/process/binary/funcs_nonstripped.go
  internal/pkg/process/binary/funcs_stripped.go
  internal/pkg/process/discover.go
  internal/pkg/process/module.go
  internal/pkg/process/ptrace/ptrace_linux.go
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog

#393 Add struct field offset tracking package: `structfield`
  internal/pkg/inject/consts.go
  internal/pkg/inject/consts_test.go
  internal/pkg/inject/data.go
  internal/pkg/inject/data_test.go
  internal/pkg/inject/offset_results.json
  internal/pkg/instrumentors/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentors/bpf/net/http/client/probe.go
  internal/pkg/instrumentors/bpf/net/http/server/probe.go
  internal/pkg/structfield/json.go
  internal/pkg/structfield/structfield.go
  internal/pkg/structfield/structfield_test.go
  internal/pkg/structfield/testdata/offsets.json
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/inspect/cache.go
  internal/tools/inspect/inspector.go
  internal/tools/inspect/manifest.go
Labels: Skip Changelog

#422 Document the need for `shareProcessNamespace` in k8s pod spec
  README.md
Labels: documentation, Skip Changelog

#414 Replace the TargetDetails Version map
  internal/pkg/inject/consts.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentors/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/process/analyze.go
  internal/pkg/process/module.go
Labels: Skip Changelog

#424 Update Makefile to run golangci-lint on tools
  Makefile
  internal/tools/inspect/manifest.go
Labels: Skip Changelog

#421 Restructure `instrumentors` package
  cli/main.go
  docs/design/context-propagation.md
  docs/design/manual-instrumentation.md
  docs/how-it-works.md
  instrumentation.go
  internal/include/arguments.h
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/database/sql/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/database/sql/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe_test.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentation/bpffs/bpfsfs.go
  internal/pkg/instrumentation/context/span_context.go
  internal/pkg/instrumentation/events/event.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/utils/ebpf.go
  internal/pkg/instrumentation/utils/kernel.go
  internal/pkg/opentelemetry/controller.go
  internal/pkg/opentelemetry/id_generator.go
  internal/pkg/process/ptrace/ptrace_linux.go
Labels: Skip Changelog

#428 Update HTTP server ebpf - add status code
  internal/include/uprobe.h
  internal/pkg/inject/offset_results.json
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/process/analyze.go
  internal/test/e2e/databasesql/traces.json
  internal/test/e2e/nethttp/traces.json
  internal/test/e2e/nethttp/verify.bats
  internal/tools/inspect/cmd/offsetgen/main.go
  internal/tools/inspect/templates/net/http/main.go.tmpl
Labels: Skip Changelog

#434 Add @RonFed as project approver 🎉
  CONTRIBUTING.md
Labels: Skip Changelog

#438 Document support of `autoexporter` package
  README.md
  cli/main.go
  instrumentation.go
Labels: documentation, Skip Changelog
