Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2024-01, with the labels that each got.

#586 Improve closing and cleaning of running probes
  instrumentation.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#579 Add probe.ID as an identifier for each probe
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe_test.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe_test.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_bpfel_arm64.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_bpfel_x86.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/probe/event.go
  internal/pkg/instrumentation/probe/manifest.go
  internal/pkg/instrumentation/probe/manifest_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/opentelemetry/controller.go
Labels: go, Skip Changelog

#605 Fix deadlock in instrumentation Close
  internal/pkg/instrumentation/manager.go
Labels: go, Skip Changelog

#606 Increase memlock limit before instrumenting
  internal/pkg/process/allocate.go
  internal/pkg/process/ptrace/ptrace_linux.go
Labels: Skip Changelog

#607 Correct ID var/field casing
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/github.com/gin-gonic/gin/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#621 Update offset_results.json
  internal/pkg/inject/offset_results.json
Labels: Skip Changelog

#623 update offsets
  internal/pkg/inject/offset_results.json
Labels: Skip Changelog

#608 Report running errors from manager and include loading errors
  internal/pkg/instrumentation/manager.go
Labels: Skip Changelog

#625 Stop ticker used for pid discovery
  internal/pkg/process/discover.go
Labels: bug, Skip Changelog

#626 Reduce flakiness, and print logs in failures
  .github/workflows/kind.yml
Labels: enhancement, Skip Changelog

#624 Remove CGO_ENABLED by using unix.Wait4
  Makefile
  internal/pkg/process/ptrace/cwrapper_linux.go
  internal/pkg/process/ptrace/ptrace_linux.go
Labels: Skip Changelog
