Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2024-10, with the labels that each got.

#1133 Add span start attributes to the SDK data
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/test/e2e/autosdk/build.sh
  internal/test/e2e/autosdk/traces.json
  internal/test/e2e/autosdk/verify.bats
  sdk/trace.go
  sdk/trace_test.go
Labels: Skip Changelog

#1134 Add span kind support to SDK and SDK probe
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/pkg/instrumentation/probe/event.go
  internal/pkg/opentelemetry/controller.go
  internal/test/e2e/autosdk/main.go
  internal/test/e2e/autosdk/traces.json
  internal/test/e2e/autosdk/verify.bats
  sdk/trace.go
  sdk/trace_test.go
Labels: Skip Changelog

#1145 Remove unneeded setup-go steps
  .github/workflows/kind.yml
Labels: Skip Changelog

#1144 Set the span status in the SDK probe
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/test/e2e/autosdk/traces.json
  internal/test/e2e/autosdk/verify.bats
Labels: Skip Changelog

#1147 Add autosdk as target library for kind workflows
  .github/workflows/kind.yml
Labels: Skip Changelog

#1136 Add span events to the SDK and SDK probe
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/pkg/instrumentation/probe/event.go
  internal/pkg/opentelemetry/controller.go
  internal/test/e2e/autosdk/traces.json
  internal/test/e2e/autosdk/verify.bats
  internal/test/test_helpers/utilities.sh
  sdk/trace.go
  sdk/trace_test.go
Labels: Skip Changelog

#981 Add env var page to docs
  README.md
  docs/configuration.md
Labels: Skip Changelog

#1151 Use a specific version of jaeger image in examples.
  examples/httpPlusdb/docker-compose.yaml
  examples/kafka-go/docker-compose.yml
  examples/rolldice/docker-compose.yaml
Labels: Skip Changelog

#1148 Add `sdk/telemetry` package
  sdk/telemetry/attr.go
  sdk/telemetry/attr_test.go
  sdk/telemetry/bench_test.go
  sdk/telemetry/doc.go
  sdk/telemetry/id.go
  sdk/telemetry/number.go
  sdk/telemetry/resource.go
  sdk/telemetry/scope.go
  sdk/telemetry/span.go
  sdk/telemetry/status.go
  sdk/telemetry/traces.go
  sdk/telemetry/value.go
Labels: Skip Changelog

#1194 Add `telemetry/test` package
  .github/dependabot.yml
  sdk/telemetry/test/conversion_test.go
  sdk/telemetry/test/doc.go
  sdk/telemetry/test/go.mod
  sdk/telemetry/test/go.sum
  versions.yaml
Labels: Skip Changelog

#1198 Remove build-context from make fixtures
  Makefile
Labels: Skip Changelog

#1202 Fix Dockerfile casing
  Dockerfile
Labels: Skip Changelog

#1199 Remove String and Size methods of TraceID and SpanID
  sdk/telemetry/id.go
Labels: Skip Changelog

#1196 Add encoding tests to the `telemetry` package
  sdk/telemetry/attr_test.go
  sdk/telemetry/conv_test.go
  sdk/telemetry/resource_test.go
  sdk/telemetry/scope.go
  sdk/telemetry/scope_test.go
  sdk/telemetry/span.go
  sdk/telemetry/span_test.go
  sdk/telemetry/test/conversion_test.go
  sdk/telemetry/traces_test.go
Labels: Skip Changelog

#1195 Use `sdk/telemetry` instead of pdata for the `autosdk` probe
  Dockerfile
  LICENSES/github.com/gogo/protobuf/LICENSE
  LICENSES/github.com/json-iterator/go/LICENSE
  LICENSES/github.com/prometheus/client_golang/prometheus/NOTICE
  LICENSES/go.opentelemetry.io/auto/sdk/telemetry/LICENSE
  LICENSES/go.opentelemetry.io/collector/pdata/LICENSE
  LICENSES/go.uber.org/multierr/LICENSE.txt
  LICENSES/golang.org/x/arch/x86/x86asm/LICENSE
  LICENSES/golang.org/x/net/LICENSE
  LICENSES/golang.org/x/sys/unix/LICENSE
  LICENSES/golang.org/x/text/LICENSE
  go.mod
  go.sum
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/test/e2e/autosdk/go.mod
  internal/test/e2e/autosdk/go.sum
  internal/test/e2e/autosdk/main.go
  sdk/LICENSE
  sdk/go.mod
  sdk/go.sum
  sdk/telemetry/id.go
  sdk/telemetry/test/go.mod
  sdk/telemetry/test/go.sum
  sdk/trace.go
  sdk/trace_test.go
Labels: Skip Changelog

#1205 Use bookworm image instead of bullseye
  Dockerfile
Labels: Skip Changelog

#1208 Fix offsets for `golang.org/x/net/http2`
  CHANGELOG.md
  internal/pkg/inject/offset_results.json
Labels: bug

#1214 Improve multi-platform builds
  Dockerfile
Labels: docker, Skip Changelog

#1216 Clean-up Makefile test target
  .github/workflows/build.yaml
  Makefile
Labels: Skip Changelog

#1217 Add CONTRIBUTING.md to sdk module
  sdk/CONTRIBUTING.md
Labels: documentation, Skip Changelog

#1232 Use CGO_ENBABLED=0 for build
  Makefile
Labels: Skip Changelog
