Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2024-07, with the labels that each got.

#899 Refactor probe loading to use ebpf.Collection
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/utils/ebpf.go
Labels: Skip Changelog, eBPF

#893 Update kafka example to use 2 services for producer and consumer
  .github/dependabot.yml
  examples/kafka-go/Dockerfile
  examples/kafka-go/README.md
  examples/kafka-go/consumer/go.mod
  examples/kafka-go/consumer/go.sum
  examples/kafka-go/consumer/main.go
  examples/kafka-go/docker-compose.yml
  examples/kafka-go/producer/go.mod
  examples/kafka-go/producer/go.sum
  examples/kafka-go/producer/main.go
  versions.yaml
Labels: Skip Changelog

#942 Ignore opentelemetry-helm-charts codespell issues
  .codespellrc
Labels: Skip Changelog

#918 Refactor span output to a common function
  Makefile
  internal/include/span_context.h
  internal/include/span_output.h
  internal/include/uprobe.h
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe_test.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
Labels: enhancement, Skip Changelog, eBPF

#907 Add instrumentation compatibility documentation
  COMPATIBILITY.md
  README.md
Labels: Skip Changelog

#945 Upgrade go-licenses from v1.6.0 to v2.0.0-alpha.1
  LICENSES/github.com/beorn7/perks/quantile/LICENSE
  LICENSES/github.com/cespare/xxhash/v2/LICENSE.txt
  LICENSES/github.com/google/uuid/LICENSE
  LICENSES/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE
  LICENSES/github.com/hashicorp/go-version/.circleci/config.yml
  LICENSES/github.com/hashicorp/go-version/.github/dependabot.yml
  LICENSES/github.com/hashicorp/go-version/.github/workflows/go-tests.yml
  LICENSES/github.com/hashicorp/go-version/CHANGELOG.md
  LICENSES/github.com/hashicorp/go-version/README.md
  LICENSES/github.com/hashicorp/go-version/constraint.go
  LICENSES/github.com/hashicorp/go-version/constraint_test.go
  LICENSES/github.com/hashicorp/go-version/version.go
  LICENSES/github.com/hashicorp/go-version/version_collection.go
  LICENSES/github.com/hashicorp/go-version/version_collection_test.go
  LICENSES/github.com/hashicorp/go-version/version_test.go
  LICENSES/github.com/munnerz/goautoneg/LICENSE
  LICENSES/github.com/pkg/errors/LICENSE
  LICENSES/github.com/prometheus/client_golang/prometheus/LICENSE
  LICENSES/github.com/prometheus/client_golang/prometheus/NOTICE
  LICENSES/github.com/prometheus/client_model/go/LICENSE
  LICENSES/github.com/prometheus/client_model/go/NOTICE
  LICENSES/github.com/prometheus/common/LICENSE
  LICENSES/github.com/prometheus/common/NOTICE
  LICENSES/go.opentelemetry.io/auto/LICENSE
  LICENSES/go.opentelemetry.io/contrib/bridges/prometheus/LICENSE
  LICENSES/go.opentelemetry.io/contrib/exporters/autoexport/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/prometheus/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/stdout/stdoutlog/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/stdout/stdoutmetric/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/LICENSE
  LICENSES/go.opentelemetry.io/otel/log/LICENSE
  LICENSES/go.opentelemetry.io/otel/metric/LICENSE
  LICENSES/go.opentelemetry.io/otel/sdk/log/LICENSE
  LICENSES/go.opentelemetry.io/otel/sdk/metric/LICENSE
  LICENSES/go.uber.org/atomic/LICENSE.txt
  LICENSES/go.uber.org/zap/LICENSE
  LICENSES/golang.org/x/exp/constraints/LICENSE
  LICENSES/golang.org/x/sys/unix/LICENSE
  LICENSES/google.golang.org/genproto/googleapis/api/httpbody/LICENSE
  LICENSES/google.golang.org/genproto/googleapis/rpc/LICENSE
  LICENSES/libbpf/bpf_tracing.h
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#947 Fix offsets for go1.22.5 and go1.21.12
  internal/pkg/inject/offset_results.json
Labels: Skip Changelog

#873 Don't track outgoing span contexts with the context map
  internal/include/go_context.h
  internal/include/uprobe.h
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
Labels: Skip Changelog, eBPF

#949 Refactor span creation
  internal/include/go_context.h
  internal/include/go_types.h
  internal/include/trace/sampling.h
  internal/include/trace/span_context.h
  internal/include/trace/span_output.h
  internal/include/trace/start_span.h
  internal/include/uprobe.h
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/database/sql/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/database/sql/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_no_tp_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_no_tp_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_x86_bpfel.go
Labels: enhancement, Skip Changelog, eBPF

#955 Fix license headers and check for license headers
  Makefile
  examples/kafka-go/consumer/main.go
  internal/include/alloc.h
  internal/include/arguments.h
  internal/include/common.h
  internal/include/go_context.h
  internal/include/go_types.h
  internal/include/otel_types.h
  internal/include/trace/sampling.h
  internal/include/trace/span_context.h
  internal/include/trace/span_output.h
  internal/include/trace/start_span.h
  internal/include/uprobe.h
  internal/include/utils.h
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
Labels: Skip Changelog

#959 Update rlimit.RemoveMemlock comment
  internal/pkg/instrumentation/manager.go
Labels: Skip Changelog

#958 Test `arm64` builds
  .github/workflows/build.yaml
Labels: Skip Changelog

#964 Document that only tracing is supported
  COMPATIBILITY.md
  README.md
Labels: documentation, Skip Changelog

#957 Update libbpf to v1.4.5
  internal/include/arguments.h
  internal/include/libbpf/bpf.h
  internal/include/libbpf/bpf_core_read.h
  internal/include/libbpf/bpf_endian.h
  internal/include/libbpf/bpf_helper_defs.h
  internal/include/libbpf/bpf_helpers.h
  internal/include/libbpf/bpf_tracing.h
  internal/include/libbpf/btf.h
  internal/include/libbpf/libbpf.h
  internal/include/libbpf/libbpf_common.h
  internal/include/libbpf/libbpf_legacy.h
  internal/include/libbpf/libbpf_version.h
  internal/include/libbpf/skel_internal.h
  internal/include/libbpf/update.sh
  internal/include/libbpf/xsk.h
Labels: Skip Changelog

#977 Fix spelling error
  .github/workflows/build.yaml
Labels: Skip Changelog

#979 Ignore built Go bin
  .gitignore
Labels: Skip Changelog
