Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2025-02, with the labels that each got.

#1739 Document we are not currently accepting new instrumentation probe PRs
  .github/ISSUE_TEMPLATE/new_instrumentation.yaml
  CONTRIBUTING.md
Labels: documentation, Skip Changelog

#1754 Rename PackageConstrainsts to PackageConstraints
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/probe/constraint.go
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#1770 Fix new instrumentation issue template
  .github/ISSUE_TEMPLATE/new_instrumentation.yaml
Labels: Skip Changelog

#1772 Fix database instrumentation for Go < 1.17
  CHANGELOG.md
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
Labels: bug

#1732 Automate the update of `libbpf`
  .github/workflows/synclibbpf.yaml
  CONTRIBUTING.md
  Makefile
  internal/include/libbpf/update.sh
  internal/tools/synclibbpf/main.go
Labels: Skip Changelog

#1799 Fix spelling error
  internal/tools/synclibbpf/main.go
Labels: documentation, Skip Changelog

#1766 Replace use of `github.com/hashicorp/go-version`
  .golangci.yml
  LICENSES/github.com/Masterminds/semver/v3/LICENSE.txt
  LICENSES/github.com/hashicorp/go-version/.github/dependabot.yml
  LICENSES/github.com/hashicorp/go-version/.github/workflows/go-tests.yml
  LICENSES/github.com/hashicorp/go-version/CHANGELOG.md
  LICENSES/github.com/hashicorp/go-version/LICENSE
  LICENSES/github.com/hashicorp/go-version/README.md
  LICENSES/github.com/hashicorp/go-version/constraint.go
  LICENSES/github.com/hashicorp/go-version/constraint_test.go
  LICENSES/github.com/hashicorp/go-version/go.mod
  LICENSES/github.com/hashicorp/go-version/version.go
  LICENSES/github.com/hashicorp/go-version/version_collection.go
  LICENSES/github.com/hashicorp/go-version/version_collection_test.go
  LICENSES/github.com/hashicorp/go-version/version_test.go
  go.mod
  go.sum
  internal/pkg/inject/consts.go
  internal/pkg/inject/consts_test.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/constraint.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/instrumentation/utils/ebpf.go
  internal/pkg/instrumentation/utils/kernel_linux.go
  internal/pkg/instrumentation/utils/kernel_linux_test.go
  internal/pkg/instrumentation/utils/kernel_other.go
  internal/pkg/process/analyze.go
  internal/pkg/process/ptrace_linux.go
  internal/pkg/structfield/json.go
  internal/pkg/structfield/structfield.go
  internal/pkg/structfield/structfield_test.go
  internal/tools/go.mod
  internal/tools/inspect/app.go
  internal/tools/inspect/builder.go
  internal/tools/inspect/cache.go
  internal/tools/inspect/cmd/offsetgen/versions.go
  internal/tools/inspect/inspector.go
  internal/tools/inspect/manifest.go
  internal/tools/synclibbpf/main.go
  versions.yaml
Labels: Skip Changelog

#1723 Update codespell Docker image definition
  .gitignore
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#1820 Ignore .cache for codespell
  .codespellrc
Labels: Skip Changelog

#1819 Document where Go registries are defined
  internal/include/arguments.h
Labels: documentation, Skip Changelog

#1815 Remove support for Go < 1.19 instrumentation
  CHANGELOG.md
  COMPATIBILITY.md
  internal/include/arguments.h
  internal/include/uprobe.h
  internal/pkg/inject/consts.go
  internal/pkg/inject/consts_test.go
  internal/pkg/inject/offset_results.json
  internal/pkg/instrumentation/bpf/database/sql/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/database/sql/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/database/sql/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/client/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_no_tp_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_no_tp_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/net/http/server/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/server/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/process/analyze.go
  internal/tools/inspect/cmd/offsetgen/main.go
  internal/tools/inspect/templates/github.com/segmentio/kafka-go/go.mod.tmpl
  internal/tools/inspect/templates/go.opentelemetry.io/otel/traceglobal/go.mod.tmpl
  internal/tools/inspect/templates/golang.org/x/net/go.mod.tmpl
  internal/tools/inspect/templates/google.golang.org/grpc/go.mod.tmpl
  internal/tools/inspect/templates/net/http/go.mod.tmpl
  internal/tools/inspect/templates/runtime/go.mod.tmpl
Labels: bug

#1884 Add project scope contributing documentation
  CONTRIBUTING.md
Labels: Skip Changelog

#1903 Rename `process.TargetDetails` to `process.Info`
  instrumentation.go
  internal/pkg/inject/consts.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpffs/bpfsfs_linux.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/process/analyze.go
Labels: Skip Changelog

#1904 Rename process.AllocationDetails to process.Allocation
  instrumentation.go
  internal/pkg/inject/consts.go
  internal/pkg/inject/consts_test.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/process/allocate.go
  internal/pkg/process/analyze.go
Labels: Skip Changelog
