Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2025-01, with the labels that each got.

#1529 Use otel-linux-arm64 for the generate and test CI, instead of macos
  .github/workflows/build.yaml
Labels: Skip Changelog

#1546 fix typo
  examples/kafka-go/docker-compose.yml
Labels: Skip Changelog

#1567 Add ebpf sampling test for multi-kernel tests
  .github/workflows/probe_load.yaml
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/sampling/sampling.go
Labels: Skip Changelog

#1566 Update the `rolldice` example
  CHANGELOG.md
  examples/rolldice/Dockerfile
  examples/rolldice/README.md
  examples/rolldice/docker-compose.yaml
  examples/rolldice/frontend/Dockerfile
  examples/rolldice/frontend/go.mod
  examples/rolldice/frontend/go.sum
  examples/rolldice/frontend/main.go
  examples/rolldice/frontend/server.go
  examples/rolldice/go.mod
  examples/rolldice/images/app.png
  examples/rolldice/images/failure.png
  examples/rolldice/images/jaeger_db.png
  examples/rolldice/images/jaeger_error.png
  examples/rolldice/images/jaeger_http.png
  examples/rolldice/images/jaeger_overview.png
  examples/rolldice/images/jaeger_trace.png
  examples/rolldice/images/success.png
  examples/rolldice/jaeger.jpg
  examples/rolldice/main.go
  examples/rolldice/user/Dockerfile
  examples/rolldice/user/client.go
  examples/rolldice/user/go.mod
  examples/rolldice/user/go.sum
  examples/rolldice/user/internal/user.go
  examples/rolldice/user/server/db.go
  examples/rolldice/user/server/main.go
  examples/rolldice/user/server/server.go
  versions.yaml
Labels: documentation

#1594 Makefile: docker-build dep of fixtures
  Makefile
Labels: Skip Changelog

#1595 Rename TargetDetails.Libraries to Modules
  instrumentation.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/process/analyze.go
Labels: Skip Changelog

#1596 Rename Manifest.Id to Manifest.ID
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/probe/manifest.go
  internal/pkg/instrumentation/probe/manifest_test.go
Labels: Skip Changelog

#1597 Flatten `internal/pkg/process/ptrace` into `process`
  internal/pkg/process/allocate.go
  internal/pkg/process/ptrace/ptrace_other.go
  internal/pkg/process/ptrace_linux.go
  internal/pkg/process/ptrace_linux_amd64.go
  internal/pkg/process/ptrace_linux_arm64.go
  internal/pkg/process/ptrace_other.go
Labels: Skip Changelog

#1607 Rename probe.StructFieldConst Val field to ID
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/auto/sdk/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#1602 Split sample build to own target
  Makefile
Labels: Skip Changelog

#1608 Unwrap StructFieldConstMinVersion for Manifests
  internal/pkg/instrumentation/probe/probe.go
Labels: Skip Changelog

#1667 chore: Clean up CONTRIBUTING.md approvers
  CONTRIBUTING.md
Labels: Skip Changelog

#1668 Move @dineshg13 to emeritus
  CONTRIBUTING.md
Labels: Skip Changelog

#1680 Moving @pdelewski to emeritus
  CONTRIBUTING.md
Labels: Skip Changelog

#1673 Group go.opentelemetry.io/build-tools updates
  renovate.json
Labels: Skip Changelog

#1666 Update getting-started.md docs
  docs/getting-started.md
Labels: documentation, Skip Changelog

#1688 Lint fixes
  .golangci.yml
  examples/httpPlusdb/main.go
  examples/kafka-go/consumer/main.go
  examples/kafka-go/producer/main.go
  examples/rolldice/frontend/server.go
  examples/rolldice/user/client.go
  examples/rolldice/user/server/db.go
  examples/rolldice/user/server/server.go
  instrumentation_test.go
  internal/pkg/inject/consts.go
  internal/pkg/instrumentation/bpf/database/sql/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/sampling/sampling.go
  internal/pkg/instrumentation/probe/sampling/utils.go
  internal/pkg/instrumentation/utils/kernel.go
  internal/pkg/instrumentation/utils/kernel_linux.go
  internal/pkg/instrumentation/utils/kernel_linux_test.go
  internal/pkg/instrumentation/utils/kernel_test.go
  internal/pkg/opentelemetry/controller_test.go
  internal/pkg/process/allocate.go
  internal/pkg/process/binary/funcs_nonstripped.go
  internal/pkg/process/binary/funcs_stripped.go
  internal/pkg/process/binary/ret_linux_amd64.go
  internal/pkg/process/discover.go
  internal/pkg/process/dwarf.go
  internal/pkg/structfield/structfield.go
  internal/test/e2e/databasesql/main.go
  internal/test/e2e/kafka-go/main.go
  internal/test/e2e/nethttp/main.go
  internal/test/e2e/nethttp_custom/main.go
  internal/tools/inspect/builder.go
  internal/tools/inspect/cmd/offsetgen/versions.go
  sdk/internal/telemetry/span.go
  sdk/internal/telemetry/value.go
  sdk/span.go
  sdk/span_test.go
  sdk/tracer.go
Labels: Skip Changelog

#1708 Run linters on arm files as well
  .github/workflows/checks.yml
  internal/pkg/process/binary/ret_linux_arm64.go
Labels: Skip Changelog

#1718 Fix DOCKERPY ownership
  Makefile
Labels: Skip Changelog

#1725 Add defensive checks for CGO stripped binaries
  internal/pkg/process/binary/funcs_stripped.go
Labels: Skip Changelog
