Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2025-04, with the labels that each got.

#2064 Fix the synclibbpf workflows config
  .github/workflows/synclibbpf.yaml
Labels: Skip Changelog

#2080 Fix renovate.json
  renovate.json
Labels: Skip Changelog

#2057 Add the `golines` formatter to golangci-lint
  .golangci.yml
  cli/main.go
  examples/httpPlusdb/main.go
  examples/kafka-go/consumer/main.go
  instrumentation.go
  instrumentation_test.go
  internal/pkg/instrumentation/bpf/database/sql/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/consumer/probe_test.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe_test.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/client/probe.go
  internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/client/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe.go
  internal/pkg/instrumentation/bpf/net/http/server/probe_test.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/probe/sampling/sampling.go
  internal/pkg/instrumentation/probe/sampling/utils.go
  internal/pkg/instrumentation/utils/ebpf.go
  internal/pkg/instrumentation/utils/kernel_linux_test.go
  internal/pkg/process/binary/funcs_nonstripped.go
  internal/pkg/process/ptrace_linux.go
  internal/pkg/structfield/structfield_test.go
  internal/test/e2e/databasesql/main.go
  internal/test/e2e/nethttp_custom/main.go
  internal/tools/inspect/builder.go
  internal/tools/inspect/cmd/offsetgen/main.go
  provider.go
  sdk/internal/telemetry/test/conversion_test.go
  sdk/limit_test.go
  sdk/span.go
  sdk/span_test.go
  sdk/tracer.go
Labels: Skip Changelog

#2089 Unify examples Dockerfile and update examples go.mod
  examples/httpPlusdb/Dockerfile
  examples/httpPlusdb/docker-compose.yaml
  examples/httpPlusdb/go.mod
  examples/httpPlusdb/http_Db_traces.jpg
  examples/kafka-go/Dockerfile
  examples/rolldice/frontend/Dockerfile
  examples/rolldice/frontend/go.mod
  examples/rolldice/user/Dockerfile
  examples/rolldice/user/go.mod
Labels: Skip Changelog

#2105 fix: fallback to no context propagation in kafka-go instrumentation if `bpf_probe_write_user` is not enabled
  CHANGELOG.md
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_no_tp_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf_no_tp_x86_bpfel.go
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/probe.go
Labels: enhancement, eBPF

#2121 fix kafka-go example
  examples/kafka-go/consumer/main.go
  examples/kafka-go/docker-compose.yml
  examples/kafka-go/producer/main.go
Labels: Skip Changelog

#2153 Consolidate GitHub workflows
  .github/workflows/build.yaml
  .github/workflows/checks.yml
  examples/httpPlusdb/go.mod
  examples/rolldice/frontend/go.mod
  examples/rolldice/user/go.mod
Labels: Skip Changelog

#2173 Remove setup-go action from integration test CI
  .github/workflows/checks.yml
Labels: Skip Changelog

#2169 Fail skipped integration tests
  .github/workflows/checks.yml
  internal/test/e2e/kafka-go/main.go
Labels: bug, Skip Changelog

#2172 Split integration tests
  .github/workflows/checks.yml
  go.mod
  internal/test/e2e/autosdk/cmd/main.go
  internal/test/e2e/autosdk/integration_test.go
  internal/test/e2e/databasesql/cmd/main.go
  internal/test/e2e/databasesql/integration_test.go
  internal/test/e2e/gin/cmd/main.go
  internal/test/e2e/gin/integration_test.go
  internal/test/e2e/go.mod
  internal/test/e2e/go.sum
  internal/test/e2e/grpc/cmd/main.go
  internal/test/e2e/grpc/integration_test.go
  internal/test/e2e/integration.go
  internal/test/e2e/kafka-go/cmd/dependencies.Dockerfile
  internal/test/e2e/kafka-go/cmd/main.go
  internal/test/e2e/kafka-go/integration_test.go
  internal/test/e2e/nethttp/cmd/main.go
  internal/test/e2e/nethttp/integration_test.go
  internal/test/e2e/nethttp_custom/cmd/main.go
  internal/test/e2e/nethttp_custom/integration_test.go
  internal/test/e2e/otelglobal/cmd/main.go
  internal/test/e2e/otelglobal/integration_test.go
Labels: Skip Changelog

#2201 Split the integration-test into a matrix test
  .github/workflows/checks.yml
Labels: Skip Changelog

#2206 Update database end-to-end program
  internal/test/e2e/databasesql/cmd/main.go
  internal/test/e2e/databasesql/verify.bats
Labels: bug, Skip Changelog

#2178 Replace BATS with Go testing in `autosdk`
  internal/test/e2e/autosdk/integration_test.go
  internal/test/e2e/go.mod
  internal/test/e2e/integration.go
  internal/test/e2e/verify.go
Labels: Skip Changelog

#2210 Replace use of BATS in database end-to-end test
  internal/test/e2e/databasesql/cmd/main.go
  internal/test/e2e/databasesql/integration_test.go
  internal/test/e2e/databasesql/verify.bats
  internal/test/e2e/verify.go
Labels: Skip Changelog

#2224 telemetry: add tests for protoInt64 and protoUint64 JSON unmarshaling
  sdk/internal/telemetry/number.go
  sdk/internal/telemetry/number_test.go
Labels: Skip Changelog

#2217 Replace BATS in kafka-go end-to-end test
  internal/test/e2e/kafka-go/integration_test.go
  internal/test/e2e/kafka-go/verify.bats
Labels: Skip Changelog

#2215 Fix end-to-end package naming
  internal/test/e2e/databasesql/integration_test.go
  internal/test/e2e/gin/integration_test.go
  internal/test/e2e/grpc/integration_test.go
  internal/test/e2e/kafka-go/integration_test.go
  internal/test/e2e/nethttp/integration_test.go
  internal/test/e2e/nethttp_custom/integration_test.go
  internal/test/e2e/otelglobal/integration_test.go
Labels: Skip Changelog

#2214 Replace BATS in gRPC end-to-end test
  internal/test/e2e/grpc/integration_test.go
  internal/test/e2e/grpc/verify.bats
Labels: Skip Changelog

#2220 Replace BATS in nonrecording end-to-end test
  internal/test/e2e/nonrecording/integration_test.go
  internal/test/e2e/nonrecording/verify.bats
Labels: Skip Changelog

#2219 Replace BATS in nethttp_custom end-to-end test
  internal/test/e2e/nethttp_custom/integration_test.go
  internal/test/e2e/nethttp_custom/verify.bats
Labels: Skip Changelog

#2221 Replace BATS in nonrecording end-to-end test
  internal/test/e2e/otelglobal/integration_test.go
  internal/test/e2e/otelglobal/verify.bats
Labels: Skip Changelog

#2229 Change AttributesMap to return map[string]any
  internal/test/e2e/autosdk/integration_test.go
  internal/test/e2e/databasesql/integration_test.go
  internal/test/e2e/gin/integration_test.go
  internal/test/e2e/grpc/integration_test.go
  internal/test/e2e/kafka-go/integration_test.go
  internal/test/e2e/nethttp/integration_test.go
  internal/test/e2e/nethttp_custom/integration_test.go
  internal/test/e2e/nonrecording/integration_test.go
  internal/test/e2e/otelglobal/integration_test.go
  internal/test/e2e/verify.go
Labels: Skip Changelog

#2239 Remove leftover `verify.bats` from autosdk
  internal/test/e2e/autosdk/verify.bats
Labels: Skip Changelog

#2237 Remove TestIntegration from e2e
  internal/test/e2e/integration.go
Labels: Skip Changelog
