Repository open-telemetry/opentelemetry-go-instrumentation, pull requests merged in 2025-03, with the labels that each got.

#1848 Crosslink modules
  Dockerfile
  Makefile
  examples/kafka-go/consumer/go.mod
  examples/kafka-go/consumer/go.sum
  examples/rolldice/frontend/go.mod
  examples/rolldice/user/go.mod
  examples/rolldice/user/go.sum
  go.mod
  go.sum
  internal/test/e2e/grpc/Dockerfile
  internal/test/e2e/grpc/build.sh
  internal/test/e2e/grpc/go.mod
  internal/test/e2e/grpc/go.sum
  internal/test/e2e/otelglobal/Dockerfile
  internal/test/e2e/otelglobal/build.sh
  internal/test/e2e/otelglobal/go.mod
  internal/test/e2e/otelglobal/go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#1906 Move probe initialization to `auto`
  instrumentation.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/manager_test.go
Labels: Skip Changelog

#1914 Fix spelling error
  docs/configuration.md
Labels: bug, documentation, Skip Changelog

#1931 Exclude crosslink of examples
  Makefile
  examples/kafka-go/consumer/go.mod
  examples/kafka-go/consumer/go.sum
  examples/rolldice/frontend/go.mod
  examples/rolldice/user/go.mod
  examples/rolldice/user/go.sum
Labels: Skip Changelog

#1916 Add the `ID` type to the `process` package
  instrumentation.go
  instrumentation_test.go
  internal/pkg/inject/consts.go
  internal/pkg/instrumentation/bpffs/bpfsfs_linux.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/process/allocate.go
  internal/pkg/process/analyze.go
  internal/pkg/process/discover.go
  internal/pkg/process/id.go
  internal/pkg/process/id_test.go
  internal/pkg/process/ptrace_linux.go
  internal/pkg/process/ptrace_other.go
Labels: Skip Changelog

#1960 fix legacy otel global instrumentation parsing
  CHANGELOG.md
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf/probe.bpf.c
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_arm64_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/bpf_x86_bpfel.go
  internal/pkg/instrumentation/bpf/go.opentelemetry.io/otel/traceglobal/probe.go
Labels: bug

#1935 remove .PHONY for sample-app docker builds
  Makefile
Labels: Skip Changelog

#1971 auto/sdk: use stack allocated span context passed to eBPF
  sdk/tracer.go
Labels: Skip Changelog

#1943 Move process Info creation into NewManager
  instrumentation.go
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/manager_test.go
Labels: Skip Changelog

#1941 Replace `Analyzer` with `NewInfo` function
  internal/pkg/instrumentation/manager.go
  internal/pkg/process/analyze.go
  internal/pkg/process/discover.go
  internal/pkg/process/info.go
Labels: Skip Changelog

#1991 Test probe load with mocks
  .github/workflows/probe_load.yaml
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/manager_test.go
  internal/pkg/instrumentation/testutils/testutils.go
  internal/pkg/process/info.go
Labels: Skip Changelog

#2028 Fix demo sql syntax
  examples/httpPlusdb/main.go
Labels: Skip Changelog

#1962 Add a dockerignore
  Dockerfile
  Dockerfile.dockerignore
Labels: Skip Changelog

#2031 Add `docker-dev` make target
  Dockerfile
  Makefile
Labels: Skip Changelog

#1945 Lazy allocate memory for process
  internal/pkg/instrumentation/manager.go
  internal/pkg/instrumentation/manager_load_test.go
  internal/pkg/instrumentation/probe/probe.go
  internal/pkg/process/allocate.go
  internal/pkg/process/info.go
  internal/pkg/process/info_test.go
Labels: Skip Changelog

#1937 zero each kafka span before populating
  CHANGELOG.md
  internal/pkg/instrumentation/bpf/github.com/segmentio/kafka-go/producer/bpf/probe.bpf.c
Labels: bug
